spring:
  application:
      name: student_service
  datasource:
    url: jdbc:mysql://localhost/mybatis?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 12345678
    driver-class-name: com.mysql.jdbc.Driver

server:
  port: 9998

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
